version: "3.8"

services:
  python-app:
    image: python:3.9
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      /bin/bash -c "
      python -m venv venv && 
      source venv/bin/activate && 
      pip install poetry && 
      poetry config virtualenvs.in-project true && 
      poetry install && 
      poetry run python3 main.py
      "
